CREATE DATABASE SUPPLY_CHAIN;
USE SUPPLY_CHAIN;
SELECT * FROM CARRIERS;
SELECT * FROM INVENTORY;
SELECT * FROM LOGISTICS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ROUTES;
SELECT * FROM SUPPLIERS;


# TOP REVENUE GENERATING PRODUCTS

SELECT P.PRODUCT_TYPE,SUM(O.REVENUE) AS TOTAL_REVENUE
FROM PRODUCTS P JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_TYPE
ORDER BY TOTAL_REVENUE DESC;

# COUNT OF CUSTOMER BY GENDER

SELECT
CUSTOMER_GENDER, 
COUNT(CUSTOMER_GENDER) AS COUNT_ 
FROM ORDERS GROUP BY CUSTOMER_GENDER;

# AVERAGE LEAD TIME BY SUPPLIER

SELECT S.SUPPLIER_NAME, ROUND(AVG(O.LEAD_TIME_DAYS)) AS LEADTIME
FROM SUPPLIERS S JOIN ORDERS O ON S.SUPPLIER_ID = O.SUPPLIER_ID
GROUP BY S.SUPPLIER_NAME 
ORDER BY LEADTIME ASC;

# REVENUE BY GENDER 

SELECT CUSTOMER_GENDER, SUM(REVENUE) AS TOTAL_REVENUE
FROM ORDERS GROUP BY CUSTOMER_GENDER;

# MOST COST EFFICIENT TRANSPORTATION MODE

SELECT R.TRANSPORTATION_MODE,
ROUND(AVG(L.SHIPPING_COST),2) AS AVERAGE_COST
FROM ROUTES R JOIN LOGISTICS L ON R.ROUTE_ID = L.ROUTE_ID
GROUP BY R.TRANSPORTATION_MODE 
ORDER BY AVERAGE_COST;

#SUPPLIERS WITH HIGHEST DEFECT RATES

SELECT S.SUPPLIER_NAME, ROUND(AVG(L.DEFECT_RATE),2) AS DEFECT_RATE
FROM SUPPLIERS S JOIN ORDERS O ON S.SUPPLIER_ID = O.SUPPLIER_ID
JOIN LOGISTICS L 
ON O.ORDER_ID = L.ORDER_ID
GROUP BY SUPPLIER_NAME
ORDER BY DEFECT_RATE DESC;

# SUPPLIERS ABOVE AVERAGE DEFECT RATES

WITH SUPPLIERS_DEFECT AS(
	SELECT S.SUPPLIER_NAME, ROUND(AVG(L.DEFECT_RATE),2) AS AVG_DEFECT_RATE
	FROM SUPPLIERS S JOIN ORDERS O ON S.SUPPLIER_ID = O.SUPPLIER_ID
	JOIN LOGISTICS L ON O.ORDER_ID = L.ORDER_ID
	GROUP BY S.SUPPLIER_NAME)
SELECT * FROM SUPPLIERS_DEFECT 
WHERE AVG_DEFECT_RATE >
	(SELECT AVG(AVG_DEFECT_RATE)
	FROM SUPPLIERS_DEFECT);

# FIND PRODUCTS WITH LOW STOCK

WITH STOCK AS(
	SELECT 
		PRODUCT_TYPE, 
        AVG(I.STOCK_LEVELS) AS STOCK_LEVEL
		FROM PRODUCTS P JOIN INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
		GROUP BY PRODUCT_TYPE)
SELECT * FROM STOCK
WHERE STOCK_LEVEL < 50;

# SUPPLIER REVENUE_REPORT 

WITH SUPPLIER AS(
	SELECT S.SUPPLIER_NAME, ROUND(AVG(O.REVENUE)) AS AVG_REVENUE
	FROM SUPPLIERS S 
	JOIN ORDERS O ON S.SUPPLIER_ID = O.SUPPLIER_ID
    GROUP BY SUPPLIER_NAME)
SELECT * FROM SUPPLIER
ORDER BY AVG_REVENUE DESC;

# WHICH SUPPLIERS PROVIDE THE HIGHEST QUALITY PRODUCTS

SELECT 
	S.SUPPLIER_NAME, 
	ROUND(AVG(L.QUALITY_SCORE),2) AS AVG_QUALITY_SCORE,
	RANK() OVER(
		ORDER BY AVG(L.QUALITY_SCORE) DESC
        ) AS QUALITY_RANK
FROM SUPPLIERS S JOIN ORDERS O ON S.SUPPLIER_ID = O.SUPPLIER_ID
JOIN LOGISTICS L ON O.ORDER_ID = L.ORDER_ID
GROUP BY SUPPLIER_NAME;

